language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack: nmk-software:xaOUI6cPbSGZpcAxyQ9uGsJh
  email:
      recipients:
        - fmpedroporras@gmail.com
        
      on_success: always
      on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 6743509a-18d2-4530-9060-892ab7ef5435
  app: curso-platzi-store
  on:
    repo: pedroporras/platzi-store-backend
